default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: parts_unknown_development

test:
  <<: *default
  database: parts_unknown_test

production:
  <<: *default
  database: parts_unknown_production
  url: <%= ENV['DATABASE_URL'] %>
